name: e2e tests

# Controls when the action will run. 
on:
  # Triggers the workflow on pull request events to main
  pull_request:
    branches: [ master ]
  # Manual trigger e2e tests
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Run Cypress e2e Tests'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains one jobs "e2e"
  e2e:
    # The type of runner that the job will run on
    runs-on: ubuntu-16.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: yarn run dev
          wait-on: http://localhost:3000
          browser: chrome
          headless: true
          spec: cypress/integration/**.spec.js
